// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metainfo.proto

package metainfo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type MetaDataRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaDataRequest) Reset()         { *m = MetaDataRequest{} }
func (m *MetaDataRequest) String() string { return proto.CompactTextString(m) }
func (*MetaDataRequest) ProtoMessage()    {}
func (*MetaDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{0}
}

func (m *MetaDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaDataRequest.Unmarshal(m, b)
}
func (m *MetaDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaDataRequest.Marshal(b, m, deterministic)
}
func (m *MetaDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaDataRequest.Merge(m, src)
}
func (m *MetaDataRequest) XXX_Size() int {
	return xxx_messageInfo_MetaDataRequest.Size(m)
}
func (m *MetaDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetaDataRequest proto.InternalMessageInfo

func (m *MetaDataRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MetaDataRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PluginID struct {
	MetaId               string   `protobuf:"bytes,1,opt,name=metaId,proto3" json:"metaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginID) Reset()         { *m = PluginID{} }
func (m *PluginID) String() string { return proto.CompactTextString(m) }
func (*PluginID) ProtoMessage()    {}
func (*PluginID) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{1}
}

func (m *PluginID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginID.Unmarshal(m, b)
}
func (m *PluginID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginID.Marshal(b, m, deterministic)
}
func (m *PluginID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginID.Merge(m, src)
}
func (m *PluginID) XXX_Size() int {
	return xxx_messageInfo_PluginID.Size(m)
}
func (m *PluginID) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginID.DiscardUnknown(m)
}

var xxx_messageInfo_PluginID proto.InternalMessageInfo

func (m *PluginID) GetMetaId() string {
	if m != nil {
		return m.MetaId
	}
	return ""
}

type ID struct {
	PluginID             *PluginID `protobuf:"bytes,1,opt,name=PluginID,json=pluginID,proto3" json:"PluginID,omitempty"`
	Version              string    `protobuf:"bytes,2,opt,name=Version,json=version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{2}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetPluginID() *PluginID {
	if m != nil {
		return m.PluginID
	}
	return nil
}

func (m *ID) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Author struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	URI                  string   `protobuf:"bytes,2,opt,name=URI,json=uRI,proto3" json:"URI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{3}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Author) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

type Dependencies struct {
	MetaDependency       []*Dependency `protobuf:"bytes,1,rep,name=metaDependency,proto3" json:"metaDependency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Dependencies) Reset()         { *m = Dependencies{} }
func (m *Dependencies) String() string { return proto.CompactTextString(m) }
func (*Dependencies) ProtoMessage()    {}
func (*Dependencies) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{4}
}

func (m *Dependencies) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependencies.Unmarshal(m, b)
}
func (m *Dependencies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependencies.Marshal(b, m, deterministic)
}
func (m *Dependencies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependencies.Merge(m, src)
}
func (m *Dependencies) XXX_Size() int {
	return xxx_messageInfo_Dependencies.Size(m)
}
func (m *Dependencies) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependencies.DiscardUnknown(m)
}

var xxx_messageInfo_Dependencies proto.InternalMessageInfo

func (m *Dependencies) GetMetaDependency() []*Dependency {
	if m != nil {
		return m.MetaDependency
	}
	return nil
}

type Interface struct {
	Interface            string   `protobuf:"bytes,1,opt,name=Interface,json=interface,proto3" json:"Interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interface) Reset()         { *m = Interface{} }
func (m *Interface) String() string { return proto.CompactTextString(m) }
func (*Interface) ProtoMessage()    {}
func (*Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{5}
}

func (m *Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface.Unmarshal(m, b)
}
func (m *Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface.Marshal(b, m, deterministic)
}
func (m *Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface.Merge(m, src)
}
func (m *Interface) XXX_Size() int {
	return xxx_messageInfo_Interface.Size(m)
}
func (m *Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_Interface proto.InternalMessageInfo

func (m *Interface) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

type Dependency struct {
	ID                   *PluginID  `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Constraint           string     `protobuf:"bytes,2,opt,name=Constraint,json=constraint,proto3" json:"Constraint,omitempty"`
	Interface            *Interface `protobuf:"bytes,3,opt,name=Interface,json=interface,proto3" json:"Interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Dependency) Reset()         { *m = Dependency{} }
func (m *Dependency) String() string { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()    {}
func (*Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{6}
}

func (m *Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependency.Unmarshal(m, b)
}
func (m *Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependency.Marshal(b, m, deterministic)
}
func (m *Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependency.Merge(m, src)
}
func (m *Dependency) XXX_Size() int {
	return xxx_messageInfo_Dependency.Size(m)
}
func (m *Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_Dependency proto.InternalMessageInfo

func (m *Dependency) GetID() *PluginID {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Dependency) GetConstraint() string {
	if m != nil {
		return m.Constraint
	}
	return ""
}

func (m *Dependency) GetInterface() *Interface {
	if m != nil {
		return m.Interface
	}
	return nil
}

type Description struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Description) Reset()         { *m = Description{} }
func (m *Description) String() string { return proto.CompactTextString(m) }
func (*Description) ProtoMessage()    {}
func (*Description) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{7}
}

func (m *Description) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Description.Unmarshal(m, b)
}
func (m *Description) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Description.Marshal(b, m, deterministic)
}
func (m *Description) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Description.Merge(m, src)
}
func (m *Description) XXX_Size() int {
	return xxx_messageInfo_Description.Size(m)
}
func (m *Description) XXX_DiscardUnknown() {
	xxx_messageInfo_Description.DiscardUnknown(m)
}

var xxx_messageInfo_Description proto.InternalMessageInfo

func (m *Description) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Description) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Core struct {
	VersionConstraint    string   `protobuf:"bytes,1,opt,name=VersionConstraint,json=versionConstraint,proto3" json:"VersionConstraint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Core) Reset()         { *m = Core{} }
func (m *Core) String() string { return proto.CompactTextString(m) }
func (*Core) ProtoMessage()    {}
func (*Core) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{8}
}

func (m *Core) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Core.Unmarshal(m, b)
}
func (m *Core) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Core.Marshal(b, m, deterministic)
}
func (m *Core) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Core.Merge(m, src)
}
func (m *Core) XXX_Size() int {
	return xxx_messageInfo_Core.Size(m)
}
func (m *Core) XXX_DiscardUnknown() {
	xxx_messageInfo_Core.DiscardUnknown(m)
}

var xxx_messageInfo_Core proto.InternalMessageInfo

func (m *Core) GetVersionConstraint() string {
	if m != nil {
		return m.VersionConstraint
	}
	return ""
}

type License struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,json=title,proto3" json:"Title,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	URI                  string   `protobuf:"bytes,3,opt,name=URI,json=uRI,proto3" json:"URI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *License) Reset()         { *m = License{} }
func (m *License) String() string { return proto.CompactTextString(m) }
func (*License) ProtoMessage()    {}
func (*License) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{9}
}

func (m *License) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_License.Unmarshal(m, b)
}
func (m *License) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_License.Marshal(b, m, deterministic)
}
func (m *License) XXX_Merge(src proto.Message) {
	xxx_messageInfo_License.Merge(m, src)
}
func (m *License) XXX_Size() int {
	return xxx_messageInfo_License.Size(m)
}
func (m *License) XXX_DiscardUnknown() {
	xxx_messageInfo_License.DiscardUnknown(m)
}

var xxx_messageInfo_License proto.InternalMessageInfo

func (m *License) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *License) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *License) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

type Link struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,json=title,proto3" json:"Title,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,json=uRL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{10}
}

func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (m *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(m, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Link) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type Links struct {
	Link                 []*Link  `protobuf:"bytes,1,rep,name=Link,json=link,proto3" json:"Link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Links) Reset()         { *m = Links{} }
func (m *Links) String() string { return proto.CompactTextString(m) }
func (*Links) ProtoMessage()    {}
func (*Links) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{11}
}

func (m *Links) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Links.Unmarshal(m, b)
}
func (m *Links) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Links.Marshal(b, m, deterministic)
}
func (m *Links) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Links.Merge(m, src)
}
func (m *Links) XXX_Size() int {
	return xxx_messageInfo_Links.Size(m)
}
func (m *Links) XXX_DiscardUnknown() {
	xxx_messageInfo_Links.DiscardUnknown(m)
}

var xxx_messageInfo_Links proto.InternalMessageInfo

func (m *Links) GetLink() []*Link {
	if m != nil {
		return m.Link
	}
	return nil
}

type Repository struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	URI                  string   `protobuf:"bytes,2,opt,name=URI,json=uRI,proto3" json:"URI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{12}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Repository) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

// The response message containing the greetings
type MetaDataReply struct {
	MetaID               *ID           `protobuf:"bytes,1,opt,name=metaID,proto3" json:"metaID,omitempty"`
	Author               *Author       `protobuf:"bytes,2,opt,name=Author,json=author,proto3" json:"Author,omitempty"`
	DependenciesArray    *Dependencies `protobuf:"bytes,3,opt,name=DependenciesArray,json=dependenciesArray,proto3" json:"DependenciesArray,omitempty"`
	Description          *Description  `protobuf:"bytes,4,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	Core                 *Core         `protobuf:"bytes,5,opt,name=Core,json=core,proto3" json:"Core,omitempty"`
	Interface            *Interface    `protobuf:"bytes,6,opt,name=Interface,json=interface,proto3" json:"Interface,omitempty"`
	License              *License      `protobuf:"bytes,7,opt,name=License,json=license,proto3" json:"License,omitempty"`
	Links                *Links        `protobuf:"bytes,8,opt,name=Links,json=links,proto3" json:"Links,omitempty"`
	Repository           *Repository   `protobuf:"bytes,9,opt,name=Repository,json=repository,proto3" json:"Repository,omitempty"`
	Tags                 []string      `protobuf:"bytes,10,rep,name=Tags,json=tags,proto3" json:"Tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MetaDataReply) Reset()         { *m = MetaDataReply{} }
func (m *MetaDataReply) String() string { return proto.CompactTextString(m) }
func (*MetaDataReply) ProtoMessage()    {}
func (*MetaDataReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e2f30a93cd64e, []int{13}
}

func (m *MetaDataReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaDataReply.Unmarshal(m, b)
}
func (m *MetaDataReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaDataReply.Marshal(b, m, deterministic)
}
func (m *MetaDataReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaDataReply.Merge(m, src)
}
func (m *MetaDataReply) XXX_Size() int {
	return xxx_messageInfo_MetaDataReply.Size(m)
}
func (m *MetaDataReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaDataReply.DiscardUnknown(m)
}

var xxx_messageInfo_MetaDataReply proto.InternalMessageInfo

func (m *MetaDataReply) GetMetaID() *ID {
	if m != nil {
		return m.MetaID
	}
	return nil
}

func (m *MetaDataReply) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *MetaDataReply) GetDependenciesArray() *Dependencies {
	if m != nil {
		return m.DependenciesArray
	}
	return nil
}

func (m *MetaDataReply) GetDescription() *Description {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *MetaDataReply) GetCore() *Core {
	if m != nil {
		return m.Core
	}
	return nil
}

func (m *MetaDataReply) GetInterface() *Interface {
	if m != nil {
		return m.Interface
	}
	return nil
}

func (m *MetaDataReply) GetLicense() *License {
	if m != nil {
		return m.License
	}
	return nil
}

func (m *MetaDataReply) GetLinks() *Links {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *MetaDataReply) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *MetaDataReply) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*MetaDataRequest)(nil), "metainfo.MetaDataRequest")
	proto.RegisterType((*PluginID)(nil), "metainfo.PluginID")
	proto.RegisterType((*ID)(nil), "metainfo.ID")
	proto.RegisterType((*Author)(nil), "metainfo.Author")
	proto.RegisterType((*Dependencies)(nil), "metainfo.Dependencies")
	proto.RegisterType((*Interface)(nil), "metainfo.Interface")
	proto.RegisterType((*Dependency)(nil), "metainfo.Dependency")
	proto.RegisterType((*Description)(nil), "metainfo.Description")
	proto.RegisterType((*Core)(nil), "metainfo.Core")
	proto.RegisterType((*License)(nil), "metainfo.License")
	proto.RegisterType((*Link)(nil), "metainfo.Link")
	proto.RegisterType((*Links)(nil), "metainfo.Links")
	proto.RegisterType((*Repository)(nil), "metainfo.Repository")
	proto.RegisterType((*MetaDataReply)(nil), "metainfo.MetaDataReply")
}

func init() { proto.RegisterFile("metainfo.proto", fileDescriptor_631e2f30a93cd64e) }

var fileDescriptor_631e2f30a93cd64e = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0xc7, 0x9f, 0x36, 0xe9, 0xdb, 0xe9, 0xde, 0xea, 0x67, 0x8c, 0x80, 0x10, 0xaa, 0x2c, 0x90,
	0x86, 0x86, 0x2a, 0x51, 0x26, 0x71, 0x01, 0x37, 0x5b, 0x83, 0x50, 0xa4, 0x32, 0x26, 0x6b, 0x70,
	0x6f, 0x5a, 0x6f, 0x58, 0xcb, 0x9c, 0x10, 0xbb, 0x93, 0x72, 0xcd, 0x47, 0xe4, 0x0b, 0x21, 0xbb,
	0x4e, 0xec, 0x94, 0x82, 0xb8, 0x3c, 0xef, 0x27, 0xe7, 0xf7, 0x8f, 0x61, 0xef, 0x8e, 0x29, 0xca,
	0xc5, 0x75, 0x36, 0xc9, 0x8b, 0x4c, 0x65, 0xa8, 0x5f, 0xd9, 0xf8, 0x2d, 0xec, 0x7f, 0x64, 0x8a,
	0xc6, 0x54, 0x51, 0xc2, 0xbe, 0xaf, 0x98, 0x54, 0x68, 0x0f, 0xda, 0x7c, 0x19, 0xb5, 0xc6, 0xad,
	0xe3, 0x01, 0x69, 0xf3, 0x25, 0x8a, 0xa0, 0x77, 0xcf, 0x0a, 0xc9, 0x33, 0x11, 0xb5, 0x8d, 0xb3,
	0x32, 0x31, 0x86, 0xfe, 0x65, 0xba, 0xba, 0xe1, 0x22, 0x89, 0xd1, 0x11, 0x74, 0x75, 0xd3, 0xa4,
	0xaa, 0xb4, 0x16, 0xbe, 0x80, 0x76, 0x12, 0xa3, 0x89, 0xcb, 0x34, 0xf1, 0xe1, 0x14, 0x4d, 0xea,
	0x9d, 0xaa, 0x08, 0xe9, 0xe7, 0x55, 0xb7, 0x08, 0x7a, 0x5f, 0xb6, 0xcf, 0x9c, 0x40, 0xf7, 0x6c,
	0xa5, 0xbe, 0x65, 0x05, 0x42, 0x10, 0x5e, 0xd0, 0x3b, 0x66, 0xe7, 0x85, 0x82, 0xde, 0x31, 0x74,
	0x00, 0xc1, 0x67, 0x92, 0xd8, 0x9a, 0x60, 0x45, 0x12, 0x3c, 0x87, 0x9d, 0x98, 0xe5, 0x4c, 0x2c,
	0x99, 0x58, 0x70, 0x26, 0xd1, 0xbb, 0xf5, 0x31, 0x6a, 0x5f, 0x19, 0xb5, 0xc6, 0xc1, 0xf1, 0x70,
	0x7a, 0xe8, 0xf6, 0x71, 0x31, 0xb2, 0x91, 0x8b, 0x5f, 0xc0, 0x20, 0x11, 0x8a, 0x15, 0xd7, 0x74,
	0xc1, 0xd0, 0x13, 0xcf, 0xb0, 0x5b, 0x0c, 0x78, 0xe5, 0xc0, 0x3f, 0x5a, 0x00, 0xae, 0x12, 0x61,
	0x7d, 0x87, 0xbf, 0x7c, 0x7b, 0x9b, 0xc7, 0xe8, 0x29, 0xc0, 0x2c, 0x13, 0x52, 0x15, 0x94, 0x0b,
	0x65, 0x3f, 0x02, 0x16, 0xb5, 0x07, 0xbd, 0xf2, 0x07, 0x06, 0xa6, 0xd5, 0xff, 0xae, 0x55, 0x1d,
	0xf2, 0xb7, 0x98, 0xc1, 0x30, 0x66, 0x72, 0x51, 0xf0, 0x5c, 0xf1, 0x4c, 0x6c, 0xbd, 0xd9, 0xb8,
	0x91, 0x62, 0xc7, 0x0e, 0x97, 0xce, 0x85, 0x4f, 0x21, 0x9c, 0x65, 0x05, 0x43, 0x2f, 0x61, 0x64,
	0xa9, 0x78, 0x6b, 0xae, 0x5b, 0x8d, 0xee, 0x37, 0x03, 0xf8, 0x3d, 0xf4, 0xe6, 0x7c, 0xc1, 0x84,
	0x64, 0xe8, 0x10, 0x3a, 0x57, 0x5c, 0xa5, 0xd5, 0xdc, 0x8e, 0xd2, 0x86, 0x5e, 0xe6, 0xaa, 0xcc,
	0x99, 0x9d, 0x18, 0xaa, 0x32, 0xaf, 0x01, 0x06, 0x0e, 0xe0, 0x04, 0xc2, 0x39, 0x17, 0xb7, 0x7f,
	0xe8, 0x61, 0xf2, 0xe7, 0x0e, 0xf8, 0x1c, 0x9f, 0x40, 0x47, 0xe7, 0x4b, 0x84, 0xd7, 0x85, 0x96,
	0xef, 0x9e, 0x3b, 0x94, 0xf6, 0x92, 0x30, 0xe5, 0xe2, 0x16, 0x4f, 0x01, 0x08, 0xcb, 0x33, 0xc9,
	0x55, 0x56, 0x94, 0xf5, 0x42, 0xad, 0xdf, 0x17, 0xf2, 0x14, 0xf5, 0x33, 0x80, 0x5d, 0xf7, 0xcf,
	0xe4, 0x69, 0x89, 0x9e, 0x59, 0xed, 0x57, 0x7c, 0x77, 0x3c, 0x28, 0xb1, 0xfd, 0x13, 0x62, 0x74,
	0x5c, 0x29, 0xd7, 0x34, 0x1b, 0x4e, 0x0f, 0x5c, 0xd6, 0xda, 0x4f, 0xba, 0x74, 0xad, 0xec, 0x18,
	0x46, 0xbe, 0x66, 0xcf, 0x8a, 0x82, 0x96, 0x96, 0xf7, 0xd1, 0x16, 0x99, 0x72, 0x26, 0xc9, 0x68,
	0xb9, 0x59, 0x80, 0xde, 0x34, 0xb9, 0x86, 0xa6, 0xfe, 0x81, 0x5f, 0x5f, 0x07, 0x1b, 0xb8, 0xf5,
	0xe1, 0x34, 0xee, 0xa8, 0x63, 0x2a, 0xbc, 0xc3, 0x69, 0x2f, 0x09, 0x17, 0x5a, 0x0a, 0x0d, 0x29,
	0x76, 0xff, 0x45, 0x8a, 0xe8, 0xa4, 0xd6, 0x43, 0xd4, 0x33, 0x05, 0x23, 0x1f, 0x89, 0x09, 0x90,
	0x5e, 0x6a, 0x15, 0xf3, 0xdc, 0x52, 0x8c, 0xfa, 0x26, 0x75, 0xbf, 0x49, 0x4f, 0x92, 0x4e, 0x6a,
	0x18, 0x9f, 0xfa, 0xfc, 0xa2, 0x81, 0xc9, 0xf5, 0xfe, 0x64, 0x17, 0x23, 0x50, 0x34, 0x39, 0xd3,
	0x1b, 0x19, 0xc1, 0x38, 0x30, 0x9c, 0xe9, 0x8d, 0x9c, 0x7e, 0x82, 0xbe, 0x86, 0x9a, 0x88, 0xeb,
	0x0c, 0xcd, 0x60, 0xf8, 0x81, 0xa9, 0xda, 0x7c, 0xe4, 0x1a, 0x6e, 0xbc, 0x95, 0x8f, 0x1f, 0x6e,
	0x0b, 0xe5, 0x69, 0x89, 0xff, 0x3b, 0x1f, 0x9d, 0xef, 0x56, 0x1d, 0x2e, 0xf5, 0xa3, 0x7b, 0xd9,
	0xfa, 0xda, 0x35, 0xaf, 0xef, 0xeb, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67, 0x38, 0x24, 0x64,
	0x8f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetaInfoClient is the client API for MetaInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetaInfoClient interface {
	// Sends a request for Metadata
	GetMetaInfo(ctx context.Context, in *MetaDataRequest, opts ...grpc.CallOption) (*MetaDataReply, error)
}

type metaInfoClient struct {
	cc *grpc.ClientConn
}

func NewMetaInfoClient(cc *grpc.ClientConn) MetaInfoClient {
	return &metaInfoClient{cc}
}

func (c *metaInfoClient) GetMetaInfo(ctx context.Context, in *MetaDataRequest, opts ...grpc.CallOption) (*MetaDataReply, error) {
	out := new(MetaDataReply)
	err := c.cc.Invoke(ctx, "/metainfo.MetaInfo/GetMetaInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaInfoServer is the server API for MetaInfo service.
type MetaInfoServer interface {
	// Sends a request for Metadata
	GetMetaInfo(context.Context, *MetaDataRequest) (*MetaDataReply, error)
}

// UnimplementedMetaInfoServer can be embedded to have forward compatible implementations.
type UnimplementedMetaInfoServer struct {
}

func (*UnimplementedMetaInfoServer) GetMetaInfo(ctx context.Context, req *MetaDataRequest) (*MetaDataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetaInfo not implemented")
}

func RegisterMetaInfoServer(s *grpc.Server, srv MetaInfoServer) {
	s.RegisterService(&_MetaInfo_serviceDesc, srv)
}

func _MetaInfo_GetMetaInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaInfoServer).GetMetaInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metainfo.MetaInfo/GetMetaInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaInfoServer).GetMetaInfo(ctx, req.(*MetaDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetaInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metainfo.MetaInfo",
	HandlerType: (*MetaInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetaInfo",
			Handler:    _MetaInfo_GetMetaInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metainfo.proto",
}
